/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_FC8kBApuy",
    "aws_user_pools_web_client_id": "235qakl0if7b3vss5ikehppnmi"
};


export default awsmobile;
